/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enquiry {
  'id' : string,
  'name' : string,
  'requirement' : string,
  'timestamp' : bigint,
  'phoneNumber' : string,
}
export type ExternalBlob = Uint8Array;
export interface Property {
  'id' : string,
  'propertyType' : string,
  'name' : string,
  'description' : string,
  'image' : ExternalBlob,
  'price' : bigint,
  'location' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProperty' : ActorMethod<
    [string, string, string, ExternalBlob, string, bigint, string],
    undefined
  >,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getEnquiryCount' : ActorMethod<[], bigint>,
  'getProperty' : ActorMethod<[string], Property>,
  'removeProperty' : ActorMethod<[string], undefined>,
  'searchProperties' : ActorMethod<[string], Array<Property>>,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'updateProperty' : ActorMethod<
    [string, string, string, ExternalBlob, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];