/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Enquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'requirement' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
});
export const Property = IDL.Record({
  'id' : IDL.Text,
  'propertyType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProperty' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProperty' : IDL.Func([IDL.Text], [Property], ['query']),
  'removeProperty' : IDL.Func([IDL.Text], [], []),
  'searchProperties' : IDL.Func([IDL.Text], [IDL.Vec(Property)], ['query']),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'updateProperty' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Enquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'requirement' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
  });
  const Property = IDL.Record({
    'id' : IDL.Text,
    'propertyType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProperty' : IDL.Func([IDL.Text], [Property], ['query']),
    'removeProperty' : IDL.Func([IDL.Text], [], []),
    'searchProperties' : IDL.Func([IDL.Text], [IDL.Vec(Property)], ['query']),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'updateProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };